// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUuFPiE1cmaSQ-_glFrGkemjBsfbDad2w',
    appId: '1:869265244077:web:98095581421004023e2b24',
    messagingSenderId: '869265244077',
    projectId: 'dummy-7f161',
    authDomain: 'dummy-7f161.firebaseapp.com',
    storageBucket: 'dummy-7f161.appspot.com',
    measurementId: 'G-HVF8XB4F63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqKn6s9CebPWHBQbgRqTHxfjgs_DsObJQ',
    appId: '1:869265244077:android:7ea2a7b8fafe2fb43e2b24',
    messagingSenderId: '869265244077',
    projectId: 'dummy-7f161',
    storageBucket: 'dummy-7f161.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD98kdMSPeMdqq2a5teglOE5ktPi85Yfxg',
    appId: '1:869265244077:ios:871c3f868bcf03ab3e2b24',
    messagingSenderId: '869265244077',
    projectId: 'dummy-7f161',
    storageBucket: 'dummy-7f161.appspot.com',
    iosBundleId: 'com.example.fire',
  );
}
